# Generated by Django 4.1.2 on 2022-10-17 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0005_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Model',
        ),
    ]
